/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: output.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "output.pb-c.h"
void   answer__init
                     (Answer         *message)
{
  static const Answer init_value = ANSWER__INIT;
  *message = init_value;
}
size_t answer__get_packed_size
                     (const Answer *message)
{
  assert(message->base.descriptor == &answer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t answer__pack
                     (const Answer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &answer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t answer__pack_to_buffer
                     (const Answer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &answer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Answer *
       answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Answer *)
     protobuf_c_message_unpack (&answer__descriptor,
                                allocator, len, data);
}
void   answer__free_unpacked
                     (Answer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &answer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor answer__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Answer, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uint_attrs",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Answer, uint_attrs),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "double_attrs",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Answer, double_attrs),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_attrs",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Answer, string_attrs),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Answer, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned answer__field_indices_by_name[] = {
  2,   /* field[2] = double_attrs */
  0,   /* field[0] = id */
  4,   /* field[4] = msg */
  3,   /* field[3] = string_attrs */
  1,   /* field[1] = uint_attrs */
};
static const ProtobufCIntRange answer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor answer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Answer",
  "Answer",
  "Answer",
  "",
  sizeof(Answer),
  5,
  answer__field_descriptors,
  answer__field_indices_by_name,
  1,  answer__number_ranges,
  (ProtobufCMessageInit) answer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
