/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: input.proto */

#ifndef PROTOBUF_C_input_2eproto__INCLUDED
#define PROTOBUF_C_input_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Answer Answer;


/* --- enums --- */


/* --- messages --- */

struct  Answer
{
  ProtobufCMessage base;
  uint64_t id;
  char *uint_attrs;
  char *double_attrs;
  char *string_attrs;
  char *msg;
};
#define ANSWER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&answer__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Answer methods */
void   answer__init
                     (Answer         *message);
size_t answer__get_packed_size
                     (const Answer   *message);
size_t answer__pack
                     (const Answer   *message,
                      uint8_t             *out);
size_t answer__pack_to_buffer
                     (const Answer   *message,
                      ProtobufCBuffer     *buffer);
Answer *
       answer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   answer__free_unpacked
                     (Answer *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Answer_Closure)
                 (const Answer *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor answer__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_input_2eproto__INCLUDED */
