/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: output.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "output.pb-c.h"
void   string__init
                     (String         *message)
{
  static const String init_value = STRING__INIT;
  *message = init_value;
}
size_t string__get_packed_size
                     (const String *message)
{
  assert(message->base.descriptor == &string__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t string__pack
                     (const String *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &string__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t string__pack_to_buffer
                     (const String *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &string__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
String *
       string__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (String *)
     protobuf_c_message_unpack (&string__descriptor,
                                allocator, len, data);
}
void   string__free_unpacked
                     (String *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &string__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   attr__init
                     (Attr         *message)
{
  static const Attr init_value = ATTR__INIT;
  *message = init_value;
}
size_t attr__get_packed_size
                     (const Attr *message)
{
  assert(message->base.descriptor == &attr__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t attr__pack
                     (const Attr *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &attr__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t attr__pack_to_buffer
                     (const Attr *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &attr__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Attr *
       attr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Attr *)
     protobuf_c_message_unpack (&attr__descriptor,
                                allocator, len, data);
}
void   attr__free_unpacked
                     (Attr *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &attr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set__init
                     (Set         *message)
{
  static const Set init_value = SET__INIT;
  *message = init_value;
}
size_t set__get_packed_size
                     (const Set *message)
{
  assert(message->base.descriptor == &set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set__pack
                     (const Set *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set__pack_to_buffer
                     (const Set *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Set *
       set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Set *)
     protobuf_c_message_unpack (&set__descriptor,
                                allocator, len, data);
}
void   set__free_unpacked
                     (Set *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   link__init
                     (Link         *message)
{
  static const Link init_value = LINK__INIT;
  *message = init_value;
}
size_t link__get_packed_size
                     (const Link *message)
{
  assert(message->base.descriptor == &link__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t link__pack
                     (const Link *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &link__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t link__pack_to_buffer
                     (const Link *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &link__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Link *
       link__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Link *)
     protobuf_c_message_unpack (&link__descriptor,
                                allocator, len, data);
}
void   link__free_unpacked
                     (Link *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &link__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   attr__type__init
                     (AttrType         *message)
{
  static const AttrType init_value = ATTR__TYPE__INIT;
  *message = init_value;
}
size_t attr__type__get_packed_size
                     (const AttrType *message)
{
  assert(message->base.descriptor == &attr__type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t attr__type__pack
                     (const AttrType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &attr__type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t attr__type__pack_to_buffer
                     (const AttrType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &attr__type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AttrType *
       attr__type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AttrType *)
     protobuf_c_message_unpack (&attr__type__descriptor,
                                allocator, len, data);
}
void   attr__type__free_unpacked
                     (AttrType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &attr__type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   value__init
                     (Value         *message)
{
  static const Value init_value = VALUE__INIT;
  *message = init_value;
}
size_t value__get_packed_size
                     (const Value *message)
{
  assert(message->base.descriptor == &value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t value__pack
                     (const Value *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t value__pack_to_buffer
                     (const Value *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Value *
       value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Value *)
     protobuf_c_message_unpack (&value__descriptor,
                                allocator, len, data);
}
void   value__free_unpacked
                     (Value *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ast__init
                     (Ast         *message)
{
  static const Ast init_value = AST__INIT;
  *message = init_value;
}
size_t ast__get_packed_size
                     (const Ast *message)
{
  assert(message->base.descriptor == &ast__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ast__pack
                     (const Ast *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ast__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ast__pack_to_buffer
                     (const Ast *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ast__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ast *
       ast__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ast *)
     protobuf_c_message_unpack (&ast__descriptor,
                                allocator, len, data);
}
void   ast__free_unpacked
                     (Ast *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ast__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor string__field_descriptors[2] =
{
  {
    "size",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(String, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(String, str),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned string__field_indices_by_name[] = {
  0,   /* field[0] = size */
  1,   /* field[1] = str */
};
static const ProtobufCIntRange string__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor string__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "String",
  "String",
  "String",
  "",
  sizeof(String),
  2,
  string__field_descriptors,
  string__field_indices_by_name,
  1,  string__number_ranges,
  (ProtobufCMessageInit) string__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor attr__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Attr, type),
    &val_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(Attr, i),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Attr, d),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Attr, str),
    &string__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Attr, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned attr__field_indices_by_name[] = {
  4,   /* field[4] = b */
  2,   /* field[2] = d */
  1,   /* field[1] = i */
  3,   /* field[3] = str */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange attr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor attr__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Attr",
  "Attr",
  "Attr",
  "",
  sizeof(Attr),
  5,
  attr__field_descriptors,
  attr__field_indices_by_name,
  1,  attr__number_ranges,
  (ProtobufCMessageInit) attr__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set__field_descriptors[3] =
{
  {
    "node_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Set, node_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attr_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Set, attr_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Set, new_value),
    &attr__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set__field_indices_by_name[] = {
  1,   /* field[1] = attr_name */
  2,   /* field[2] = new_value */
  0,   /* field[0] = node_id */
};
static const ProtobufCIntRange set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Set",
  "Set",
  "Set",
  "",
  sizeof(Set),
  3,
  set__field_descriptors,
  set__field_indices_by_name,
  1,  set__number_ranges,
  (ProtobufCMessageInit) set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor link__field_descriptors[2] =
{
  {
    "link_id_one",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Link, link_id_one),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "link_id_two",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Link, link_id_two),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned link__field_indices_by_name[] = {
  0,   /* field[0] = link_id_one */
  1,   /* field[1] = link_id_two */
};
static const ProtobufCIntRange link__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor link__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Link",
  "Link",
  "Link",
  "",
  sizeof(Link),
  2,
  link__field_descriptors,
  link__field_indices_by_name,
  1,  link__number_ranges,
  (ProtobufCMessageInit) link__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor attr__type__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AttrType, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "val",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AttrType, val),
    &val_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned attr__type__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = val */
};
static const ProtobufCIntRange attr__type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor attr__type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Attr_Type",
  "AttrType",
  "AttrType",
  "",
  sizeof(AttrType),
  2,
  attr__type__field_descriptors,
  attr__type__field_indices_by_name,
  1,  attr__type__number_ranges,
  (ProtobufCMessageInit) attr__type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor value__field_descriptors[9] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Value, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Value, target),
    &insert_target__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Value, set),
    &set__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attr",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Value, attr),
    &attr__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "l_op",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Value, l_op),
    &logical_op__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmp",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Value, cmp),
    &cmp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "link",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Value, link),
    &link__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cnt",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Value, cnt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attr_type",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Value, attr_type),
    &attr__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned value__field_indices_by_name[] = {
  3,   /* field[3] = attr */
  8,   /* field[8] = attr_type */
  5,   /* field[5] = cmp */
  7,   /* field[7] = cnt */
  4,   /* field[4] = l_op */
  6,   /* field[6] = link */
  0,   /* field[0] = name */
  2,   /* field[2] = set */
  1,   /* field[1] = target */
};
static const ProtobufCIntRange value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Value",
  "Value",
  "Value",
  "",
  sizeof(Value),
  9,
  value__field_descriptors,
  value__field_indices_by_name,
  1,  value__number_ranges,
  (ProtobufCMessageInit) value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ast__field_descriptors[5] =
{
  {
    "left",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ast, left),
    &ast__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ast, right),
    &ast__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ast, type),
    &ast_node_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ast, v_type),
    &value_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "val",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ast, val),
    &value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ast__field_indices_by_name[] = {
  0,   /* field[0] = left */
  1,   /* field[1] = right */
  2,   /* field[2] = type */
  3,   /* field[3] = v_type */
  4,   /* field[4] = val */
};
static const ProtobufCIntRange ast__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ast__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ast",
  "Ast",
  "Ast",
  "",
  sizeof(Ast),
  5,
  ast__field_descriptors,
  ast__field_indices_by_name,
  1,  ast__number_ranges,
  (ProtobufCMessageInit) ast__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ast_node_type__enum_values_by_number[15] =
{
  { "FILENAME_N", "AST_NODE_TYPE__FILENAME_N", 0 },
  { "INSERT_N", "AST_NODE_TYPE__INSERT_N", 1 },
  { "SELECT_N", "AST_NODE_TYPE__SELECT_N", 2 },
  { "UPDATE_N", "AST_NODE_TYPE__UPDATE_N", 3 },
  { "DELETE_N", "AST_NODE_TYPE__DELETE_N", 4 },
  { "INDEX_N", "AST_NODE_TYPE__INDEX_N", 5 },
  { "NODE_N", "AST_NODE_TYPE__NODE_N", 6 },
  { "LINK_N", "AST_NODE_TYPE__LINK_N", 7 },
  { "CONDITIONAL_N", "AST_NODE_TYPE__CONDITIONAL_N", 8 },
  { "FILTER_N", "AST_NODE_TYPE__FILTER_N", 9 },
  { "SET_N", "AST_NODE_TYPE__SET_N", 10 },
  { "VAL_N", "AST_NODE_TYPE__VAL_N", 11 },
  { "NAME_N", "AST_NODE_TYPE__NAME_N", 12 },
  { "LIST_N", "AST_NODE_TYPE__LIST_N", 13 },
  { "ATTR_DESC_N", "AST_NODE_TYPE__ATTR_DESC_N", 14 },
};
static const ProtobufCIntRange ast_node_type__value_ranges[] = {
{0, 0},{0, 15}
};
static const ProtobufCEnumValueIndex ast_node_type__enum_values_by_name[15] =
{
  { "ATTR_DESC_N", 14 },
  { "CONDITIONAL_N", 8 },
  { "DELETE_N", 4 },
  { "FILENAME_N", 0 },
  { "FILTER_N", 9 },
  { "INDEX_N", 5 },
  { "INSERT_N", 1 },
  { "LINK_N", 7 },
  { "LIST_N", 13 },
  { "NAME_N", 12 },
  { "NODE_N", 6 },
  { "SELECT_N", 2 },
  { "SET_N", 10 },
  { "UPDATE_N", 3 },
  { "VAL_N", 11 },
};
const ProtobufCEnumDescriptor ast_node_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AstNodeType",
  "AstNodeType",
  "AstNodeType",
  "",
  15,
  ast_node_type__enum_values_by_number,
  15,
  ast_node_type__enum_values_by_name,
  1,
  ast_node_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue insert_target__enum_values_by_number[3] =
{
  { "I_NODE", "INSERT_TARGET__I_NODE", 0 },
  { "I_LINK", "INSERT_TARGET__I_LINK", 1 },
  { "I_INDEX", "INSERT_TARGET__I_INDEX", 2 },
};
static const ProtobufCIntRange insert_target__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex insert_target__enum_values_by_name[3] =
{
  { "I_INDEX", 2 },
  { "I_LINK", 1 },
  { "I_NODE", 0 },
};
const ProtobufCEnumDescriptor insert_target__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "InsertTarget",
  "InsertTarget",
  "InsertTarget",
  "",
  3,
  insert_target__enum_values_by_number,
  3,
  insert_target__enum_values_by_name,
  1,
  insert_target__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue val_type__enum_values_by_number[4] =
{
  { "INT", "VAL_TYPE__INT", 0 },
  { "DOUBLE", "VAL_TYPE__DOUBLE", 1 },
  { "STRING", "VAL_TYPE__STRING", 2 },
  { "BOOL", "VAL_TYPE__BOOL", 3 },
};
static const ProtobufCIntRange val_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex val_type__enum_values_by_name[4] =
{
  { "BOOL", 3 },
  { "DOUBLE", 1 },
  { "INT", 0 },
  { "STRING", 2 },
};
const ProtobufCEnumDescriptor val_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ValType",
  "ValType",
  "ValType",
  "",
  4,
  val_type__enum_values_by_number,
  4,
  val_type__enum_values_by_name,
  1,
  val_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue logical_op__enum_values_by_number[3] =
{
  { "AND", "LOGICAL_OP__AND", 0 },
  { "OR", "LOGICAL_OP__OR", 1 },
  { "NOT", "LOGICAL_OP__NOT", 2 },
};
static const ProtobufCIntRange logical_op__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex logical_op__enum_values_by_name[3] =
{
  { "AND", 0 },
  { "NOT", 2 },
  { "OR", 1 },
};
const ProtobufCEnumDescriptor logical_op__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "LogicalOp",
  "LogicalOp",
  "LogicalOp",
  "",
  3,
  logical_op__enum_values_by_number,
  3,
  logical_op__enum_values_by_name,
  1,
  logical_op__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue cmp__enum_values_by_number[6] =
{
  { "GT", "CMP__GT", 0 },
  { "LT", "CMP__LT", 1 },
  { "EQ", "CMP__EQ", 2 },
  { "GT_EQ", "CMP__GT_EQ", 3 },
  { "LT_EQ", "CMP__LT_EQ", 4 },
  { "SUBSTR", "CMP__SUBSTR", 5 },
};
static const ProtobufCIntRange cmp__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex cmp__enum_values_by_name[6] =
{
  { "EQ", 2 },
  { "GT", 0 },
  { "GT_EQ", 3 },
  { "LT", 1 },
  { "LT_EQ", 4 },
  { "SUBSTR", 5 },
};
const ProtobufCEnumDescriptor cmp__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Cmp",
  "Cmp",
  "Cmp",
  "",
  6,
  cmp__enum_values_by_number,
  6,
  cmp__enum_values_by_name,
  1,
  cmp__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue value_type__enum_values_by_number[10] =
{
  { "NONE", "VALUE_TYPE__NONE", 0 },
  { "NAME", "VALUE_TYPE__NAME", 1 },
  { "INSERT_TARGET", "VALUE_TYPE__INSERT_TARGET", 2 },
  { "SET", "VALUE_TYPE__SET", 3 },
  { "ATTR", "VALUE_TYPE__ATTR", 4 },
  { "LOGICAL_OP", "VALUE_TYPE__LOGICAL_OP", 5 },
  { "CMP", "VALUE_TYPE__CMP", 6 },
  { "LINK", "VALUE_TYPE__LINK", 7 },
  { "CNT", "VALUE_TYPE__CNT", 8 },
  { "ATTR_DESC", "VALUE_TYPE__ATTR_DESC", 9 },
};
static const ProtobufCIntRange value_type__value_ranges[] = {
{0, 0},{0, 10}
};
static const ProtobufCEnumValueIndex value_type__enum_values_by_name[10] =
{
  { "ATTR", 4 },
  { "ATTR_DESC", 9 },
  { "CMP", 6 },
  { "CNT", 8 },
  { "INSERT_TARGET", 2 },
  { "LINK", 7 },
  { "LOGICAL_OP", 5 },
  { "NAME", 1 },
  { "NONE", 0 },
  { "SET", 3 },
};
const ProtobufCEnumDescriptor value_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ValueType",
  "ValueType",
  "ValueType",
  "",
  10,
  value_type__enum_values_by_number,
  10,
  value_type__enum_values_by_name,
  1,
  value_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
